2024-07-12 14:23:10.033 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "5"

2024-07-12 14:24:11.353 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "7"

2024-07-12 14:24:17.484 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "17"

2024-07-12 15:48:38.307 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "35"

2024-07-12 15:48:41.386 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "40"

2024-07-12 15:49:00.712 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "69"

2024-07-12 15:49:01.945 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "71"

2024-07-12 15:49:01.961 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "72"

2024-07-12 15:49:16.187 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "109"

2024-07-12 15:50:22.976 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "192"

2024-07-12 15:50:39.836 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "222"

2024-07-12 15:50:41.928 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "233"

2024-07-12 15:51:36.786 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "268"

2024-07-12 15:51:36.789 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "267"

2024-07-12 15:51:36.876 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "271"

2024-07-12 15:51:36.880 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "270"

2024-07-12 15:51:37.684 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "269"

2024-07-12 15:51:37.750 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "273"

2024-07-12 15:51:37.752 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "275"

2024-07-12 15:51:39.230 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "274"

2024-07-12 15:51:39.280 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "276"

2024-07-12 15:51:39.282 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "278"

2024-07-12 15:51:40.665 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "277"

2024-07-12 15:51:40.707 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "279"

2024-07-12 15:51:40.708 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "281"

2024-07-12 15:51:41.119 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "280"

2024-07-12 15:51:41.141 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "282"

2024-07-12 15:51:41.142 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "283"

2024-07-12 15:51:41.541 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "285"

2024-07-12 15:51:41.543 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "286"

2024-07-12 15:51:41.951 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "284"

2024-07-12 15:51:41.970 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "287"

2024-07-12 15:51:41.971 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "288"

2024-07-12 15:51:42.135 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "289"

2024-07-12 15:51:42.168 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "291"

2024-07-12 15:51:42.399 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "292"

2024-07-12 15:51:42.404 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "290"

2024-07-12 15:51:42.602 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "296"
WARNING:pygls.protocol:Cancel notification for unknown message id "295"

2024-07-12 15:51:42.867 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "297"

2024-07-12 15:51:43.045 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "299"

2024-07-12 15:51:43.047 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "300"

2024-07-12 15:51:43.048 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "298"

2024-07-12 15:51:43.192 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "301"

2024-07-12 15:51:43.371 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "303"

2024-07-12 15:51:43.372 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "304"

2024-07-12 15:51:43.374 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "302"

2024-07-12 15:51:43.651 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "306"

2024-07-12 15:51:43.653 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "307"

2024-07-12 15:51:43.656 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "305"

2024-07-12 15:51:43.839 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "309"

2024-07-12 15:51:43.840 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "310"

2024-07-12 15:51:43.886 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "311"

2024-07-12 15:51:43.888 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "308"

2024-07-12 15:51:44.056 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "312"

2024-07-12 15:51:44.060 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "314"

2024-07-12 15:51:44.061 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "315"

2024-07-12 15:51:44.062 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "313"

2024-07-12 15:51:54.825 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "337"

2024-07-12 15:51:56.781 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "343"

2024-07-12 15:52:04.901 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "356"

2024-07-12 15:52:04.904 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "357"

2024-07-12 15:52:05.339 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "359"

2024-07-12 15:52:05.341 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "358"

2024-07-12 15:52:05.348 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "360"

2024-07-12 15:52:05.352 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "361"

2024-07-12 15:52:05.793 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "363"

2024-07-12 15:52:05.797 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "364"

2024-07-12 15:52:07.135 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "367"

2024-07-12 15:52:07.137 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "368"

2024-07-12 15:52:07.725 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "369"

2024-07-12 15:52:07.726 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "370"

2024-07-12 15:52:09.016 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "373"

2024-07-12 15:52:22.533 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "405"

2024-07-12 15:52:22.660 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "407"

2024-07-12 15:52:23.987 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "413"

2024-07-12 15:52:25.101 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "415"

2024-07-12 15:52:25.107 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "417"

2024-07-12 15:52:25.976 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "416"

2024-07-12 15:52:26.054 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "418"

2024-07-12 15:52:26.055 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "420"

2024-07-12 15:52:26.733 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "419"

2024-07-12 15:52:26.770 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "421"

2024-07-12 15:52:26.774 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "422"

2024-07-12 15:52:26.775 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "424"

2024-07-12 15:52:27.499 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "423"

2024-07-12 15:52:27.543 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "425"
WARNING:pygls.protocol:Cancel notification for unknown message id "427"

2024-07-12 15:52:35.544 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "443"

2024-07-12 15:52:35.550 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "444"

2024-07-12 15:52:37.083 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "446"

2024-07-12 15:52:37.085 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "442"

2024-07-12 15:52:37.211 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "445"

2024-07-12 15:52:37.223 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "447"

2024-07-12 15:52:37.440 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "448"

2024-07-12 15:52:37.452 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "450"

2024-07-12 15:52:37.455 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "451"

2024-07-12 15:52:37.457 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "449"

2024-07-12 15:52:37.679 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "452"

2024-07-12 15:52:58.813 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "483"

2024-07-12 15:53:00.193 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "488"

2024-07-12 15:53:26.363 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "532"

2024-07-12 15:53:27.347 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "536"

2024-07-12 15:53:27.434 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "537"

2024-07-12 15:53:27.726 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "540"

2024-07-12 15:53:46.743 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "579"

2024-07-12 15:53:52.199 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "592"

2024-07-12 15:53:52.212 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "594"

2024-07-12 15:53:53.939 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "604"

2024-07-12 15:54:21.180 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "609"

2024-07-12 15:54:22.350 [info] ERROR:pygls.protocol:Failed to handle request 613 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/karthi/Leetcode_daily_progress_scrapper/main.py'), range=33:23-33:23, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 580, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
           ^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2024-07-12 15:54:22.359 [info] [Error - 3:54:22 PM] Request textDocument/codeAction failed.
2024-07-12 15:54:22.360 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32602 
{'traceback': ['  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 580, in code_action\n    extract_variable_refactoring = jedi_script.extract_variable(\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper\n    return func(self, line, column, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable\n    return extract_variable(\n           ^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable\n    nodes = _find_nodes(module_node, pos, until_pos)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes\n    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes\n    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes\n    nodes = nodes[start_index:end_index + 1]\n                  ^^^^^^^^^^^\n']}
2024-07-12 15:56:00.457 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "621"

2024-07-12 15:56:05.163 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "637"

2024-07-12 15:56:05.426 [info] ERROR:pygls.protocol:Failed to handle request 639 completionItem/resolve CompletionItem(label='how=', label_details=None, kind=<CompletionItemKind.Variable: 6>, tags=None, detail=None, documentation=None, deprecated=None, preselect=None, sort_text='a4', filter_text='how=', insert_text='how=', insert_text_format=<InsertTextFormat.PlainText: 1>, insert_text_mode=None, text_edit=None, text_edit_text=None, additional_text_edits=None, commit_characters=None, command=None, data=None)
Traceback (most recent call last):
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 187, in completion_item_resolve
    return jedi_utils.lsp_completion_item_resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 695, in lsp_completion_item_resolve
    item.detail = next(get_full_signatures(completion), completion.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures
    signatures = name.get_signatures()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures
    for s in self._get_signatures()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
                                             ^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper
    return func(param_name)
           ^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer
    values = super().infer()
             ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer
    values = self.infer_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation
    values = values.execute_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper
    return self.from_sets(
           ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>
    getattr(value, name)(*args, **kwargs)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation
    v.with_generics(arguments)
    ^^^^^^^^^^^^^^^
AttributeError: 'TreeInstance' object has no attribute 'with_generics'

2024-07-12 15:56:05.438 [info] [Error - 3:56:05 PM] Request completionItem/resolve failed.
2024-07-12 15:56:05.438 [info]   Message: AttributeError: 'TreeInstance' object has no attribute 'with_generics'
  Code: -32602 
{'traceback': ['  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 187, in completion_item_resolve\n    return jedi_utils.lsp_completion_item_resolve(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 695, in lsp_completion_item_resolve\n    item.detail = next(get_full_signatures(completion), completion.name)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures\n    signatures = name.get_signatures()\n                 ^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures\n    for s in self._get_signatures()\n             ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures\n    return [sig for name in names for sig in name.infer().get_signatures()]\n                                             ^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper\n    return built_functions[public_name](*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper\n    return func(param_name)\n           ^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer\n    values = super().infer()\n             ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer\n    values = self.infer_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation\n    values = values.execute_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper\n    return self.from_sets(\n           ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets\n    for set_ in sets:\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>\n    getattr(value, name)(*args, **kwargs)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation\n    v.with_generics(arguments)\n    ^^^^^^^^^^^^^^^\n']}
2024-07-12 15:56:05.441 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "639"

2024-07-12 15:56:05.453 [info] ERROR:pygls.protocol:Failed to handle request 640 completionItem/resolve CompletionItem(label='how=', label_details=None, kind=<CompletionItemKind.Variable: 6>, tags=None, detail=None, documentation=None, deprecated=None, preselect=None, sort_text='a4', filter_text='how=', insert_text='how=', insert_text_format=<InsertTextFormat.PlainText: 1>, insert_text_mode=None, text_edit=None, text_edit_text=None, additional_text_edits=None, commit_characters=None, command=None, data=None)
Traceback (most recent call last):
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 187, in completion_item_resolve
    return jedi_utils.lsp_completion_item_resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 695, in lsp_completion_item_resolve
    item.detail = next(get_full_signatures(completion), completion.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures
    signatures = name.get_signatures()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures
    for s in self._get_signatures()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
                                             ^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper
    return func(param_name)
           ^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer
    values = super().infer()
             ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer
    values = self.infer_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation
    values = values.execute_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper
    return self.from_sets(
           ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>
    getattr(value, name)(*args, **kwargs)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation
    v.with_generics(arguments)
    ^^^^^^^^^^^^^^^
AttributeError: 'TreeInstance' object has no attribute 'with_generics'

2024-07-12 15:56:05.464 [info] [Error - 3:56:05 PM] Request completionItem/resolve failed.
2024-07-12 15:56:05.464 [info]   Message: AttributeError: 'TreeInstance' object has no attribute 'with_generics'
  Code: -32602 
{'traceback': ['  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 187, in completion_item_resolve\n    return jedi_utils.lsp_completion_item_resolve(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 695, in lsp_completion_item_resolve\n    item.detail = next(get_full_signatures(completion), completion.name)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures\n    signatures = name.get_signatures()\n                 ^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures\n    for s in self._get_signatures()\n             ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures\n    return [sig for name in names for sig in name.infer().get_signatures()]\n                                             ^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper\n    return built_functions[public_name](*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper\n    return func(param_name)\n           ^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer\n    values = super().infer()\n             ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer\n    values = self.infer_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation\n    values = values.execute_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper\n    return self.from_sets(\n           ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets\n    for set_ in sets:\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>\n    getattr(value, name)(*args, **kwargs)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation\n    v.with_generics(arguments)\n    ^^^^^^^^^^^^^^^\n']}
2024-07-12 15:56:05.512 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "641"

2024-07-12 15:56:06.554 [info] ERROR:pygls.protocol:Failed to handle request 646 completionItem/resolve CompletionItem(label='how=', label_details=None, kind=<CompletionItemKind.Variable: 6>, tags=None, detail=None, documentation=None, deprecated=None, preselect=None, sort_text='a4', filter_text='how=', insert_text='how=', insert_text_format=<InsertTextFormat.PlainText: 1>, insert_text_mode=None, text_edit=None, text_edit_text=None, additional_text_edits=None, commit_characters=None, command=None, data=None)
Traceback (most recent call last):
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 187, in completion_item_resolve
    return jedi_utils.lsp_completion_item_resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 695, in lsp_completion_item_resolve
    item.detail = next(get_full_signatures(completion), completion.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures
    signatures = name.get_signatures()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures
    for s in self._get_signatures()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
                                             ^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper
    return func(param_name)
           ^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer
    values = super().infer()
             ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer
    values = self.infer_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation
    values = values.execute_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper
    return self.from_sets(
           ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>
    getattr(value, name)(*args, **kwargs)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation
    v.with_generics(arguments)
    ^^^^^^^^^^^^^^^
AttributeError: 'TreeInstance' object has no attribute 'with_generics'

2024-07-12 15:56:06.565 [info] [Error - 3:56:06 PM] Request completionItem/resolve failed.
2024-07-12 15:56:06.566 [info]   Message: AttributeError: 'TreeInstance' object has no attribute 'with_generics'
  Code: -32602 
{'traceback': ['  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 187, in completion_item_resolve\n    return jedi_utils.lsp_completion_item_resolve(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 695, in lsp_completion_item_resolve\n    item.detail = next(get_full_signatures(completion), completion.name)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures\n    signatures = name.get_signatures()\n                 ^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures\n    for s in self._get_signatures()\n             ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures\n    return [sig for name in names for sig in name.infer().get_signatures()]\n                                             ^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper\n    return built_functions[public_name](*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper\n    return func(param_name)\n           ^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer\n    values = super().infer()\n             ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer\n    values = self.infer_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation\n    values = values.execute_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper\n    return self.from_sets(\n           ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets\n    for set_ in sets:\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>\n    getattr(value, name)(*args, **kwargs)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation\n    v.with_generics(arguments)\n    ^^^^^^^^^^^^^^^\n']}
2024-07-12 15:56:08.656 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "654"

2024-07-12 15:56:09.027 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "656"

2024-07-12 15:56:09.101 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "658"

2024-07-12 15:56:09.235 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "659"

2024-07-12 15:56:09.700 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "662"

2024-07-12 15:56:11.656 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "677"

2024-07-12 15:56:11.769 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "678"

2024-07-12 16:04:35.303 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "717"

2024-07-12 16:12:39.674 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "725"

2024-07-12 16:12:46.000 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "733"

2024-07-12 16:12:47.242 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "737"

2024-07-12 16:12:47.790 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "741"

2024-07-12 16:12:55.035 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "753"

2024-07-12 16:19:45.522 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "771"

2024-07-12 16:19:45.974 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "772"

2024-07-12 16:21:36.012 [info] ERROR:pygls.protocol:Failed to handle request 783 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///home/karthi/Leetcode_daily_progress_scrapper/main.py'), position=28:28, work_done_token=None)
Traceback (most recent call last):
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 383, in hover
    hover_text = jedi_utils.hover_text(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 665, in hover_text
    header_plain = "\n".join(get_full_signatures(name))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures
    signatures = name.get_signatures()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures
    for s in self._get_signatures()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
                                             ^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper
    return func(param_name)
           ^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer
    values = super().infer()
             ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer
    values = self.infer_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation
    values = values.execute_annotation()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper
    return self.from_sets(
           ^^^^^^^^^^^^^^^
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>
    getattr(value, name)(*args, **kwargs)
  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation
    v.with_generics(arguments)
    ^^^^^^^^^^^^^^^
AttributeError: 'TreeInstance' object has no attribute 'with_generics'

2024-07-12 16:21:36.024 [info] [Error - 4:21:36 PM] Request textDocument/hover failed.
2024-07-12 16:21:36.024 [info]   Message: AttributeError: 'TreeInstance' object has no attribute 'with_generics'
  Code: -32602 
{'traceback': ['  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 383, in hover\n    hover_text = jedi_utils.hover_text(\n                 ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 665, in hover_text\n    header_plain = "\\n".join(get_full_signatures(name))\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 609, in get_full_signatures\n    signatures = name.get_signatures()\n                 ^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 581, in get_signatures\n    for s in self._get_signatures()\n             ^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/api/classes.py", line 570, in _get_signatures\n    return [sig for name in names for sig in name.infer().get_signatures()]\n                                             ^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/__init__.py", line 21, in wrapper\n    return built_functions[public_name](*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/plugins/pytest.py", line 58, in wrapper\n    return func(param_name)\n           ^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 523, in infer\n    values = super().infer()\n             ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 508, in infer\n    values = self.infer_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/names.py", line 466, in infer_annotation\n    values = values.execute_annotation()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 460, in mapper\n    return self.from_sets(\n           ^^^^^^^^^^^^^^^\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 430, in from_sets\n    for set_ in sets:\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/base_value.py", line 461, in <genexpr>\n    getattr(value, name)(*args, **kwargs)\n', '  File "/home/karthi/.vscode-oss/extensions/ms-python.python-2024.10.0-universal/python_files/lib/jedilsp/jedi/inference/compiled/value.py", line 261, in execute_annotation\n    v.with_generics(arguments)\n    ^^^^^^^^^^^^^^^\n']}
2024-07-12 16:21:36.035 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "783"

2024-07-12 16:24:14.844 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "796"

2024-07-12 16:24:36.831 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "801"

2024-07-12 16:24:36.902 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "802"

2024-07-12 16:24:36.971 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "803"

2024-07-12 16:24:37.056 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "804"

2024-07-12 16:24:37.122 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "805"

2024-07-12 16:24:37.158 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "806"

2024-07-12 16:24:37.196 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "807"

2024-07-12 16:35:40.462 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "820"

2024-07-12 16:40:03.535 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "838"

2024-07-12 16:40:22.274 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "854"

2024-07-12 16:41:19.967 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "863"

2024-07-12 16:49:13.015 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "869"

2024-07-12 16:49:39.837 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "880"

2024-07-12 16:49:45.686 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "883"

2024-07-12 16:49:50.602 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "904"

2024-07-12 16:50:00.485 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "918"

2024-07-12 16:50:00.527 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "920"

2024-07-12 16:50:40.363 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "945"

2024-07-12 16:50:56.766 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "981"

2024-07-12 16:50:56.979 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "982"

2024-07-12 16:50:59.209 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "989"

2024-07-12 16:50:59.355 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "990"

2024-07-12 16:51:01.479 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "1000"

2024-07-12 16:51:01.675 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "1003"

2024-07-12 16:51:10.904 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "1033"

2024-07-12 16:51:29.240 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "1061"

